spring:
    application:
        name: PlayMap

    datasource:
        url: jdbc:postgresql://localhost:5432/place
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update # ?? validate / none / create-drop
        properties:
            hibernate:
                dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
        show-sql: true
        open-in-view: false

profiles:
active: local

logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.type: trace
